- name: Install required dependencies
  ansible.builtin.apt:
    name: '{{ docker_deps }}'
    update_cache: true

- name: Add Docker's official GPG key
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL {{ docker_gpg_key }} -o {{ docker_keyring_path }}
    chmod a+r {{ docker_keyring_path }}
  args:
    executable: /bin/bash
    creates: '{{ docker_keyring_path }}'

- name: Copy Docker's repository setup
  ansible.builtin.copy:
    src: docker.repo.sh
    dest: /tmp/docker.repo.sh
    mode: '0775'

- name: Add Docker's repository
  ansible.builtin.shell: /tmp/docker.repo.sh
  args:
    executable: /bin/bash
    creates: /etc/apt/sources.list.d/docker.list

- name: Install Docker packages
  ansible.builtin.apt:
    name: '{{ docker_packages }}'
    update_cache: true
