name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./node_api

      - name: Build the project
        run: npm run build
        working-directory: ./node_api

      - name: Run tests
        run: npm test
        working-directory: ./node_api

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_EC2_KEY }}

      - name: Add Server IP to known hosts
        run: |
          SERVER_IP=$(awk 'NR > 1 {print $1}' < ../ansible/inventory.ini)
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini deploy.yaml
        working-directory: ./ansible
